image:
  file: .gitpod.Dockerfile
tasks:
  - name: Clippy
    init: cargo clippy --all --features=stable -- -D clippy::result_unwrap_used -D clippy::option_unwrap_used
  - name: Testing
    init: cargo test --all --features=stable
  - name: Build
    init: cargo build --features=stable
  - name: Nu
    init: cargo install --path . --features=stable
    command: nu
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addLabel: prebuilt-in-gitpod
