[package]
name = "crypto_check"
version = "0.1.0"
authors = ["Kai <kai.park1201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
reqwest = "0.11.0"
